services:
  exe201.smartthrive.api:
    image: sonnh37/exe201smartthriveapi
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exe201.smartthrive.api
    ports:
      - "9876:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__SmartThrive=Server=host.docker.internal,1433;Database=SmartThrive;User Id=sa;Password=sa;TrustServerCertificate=True; 
    networks:
      - my_network

networks:
  my_network:
    driver: bridge  